# Generated by Django 4.0.5 on 2024-06-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0003_rename_action_testcases_bady_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='staff',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='userstory',
            new_name='userstory_d',
        ),
    ]
